import './globals.css'
import { Inter } from 'next/font/google'
import { QueryProvider } from '@/lib/QueryProvider'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Front-End Friend',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={cn('bg-white font-sans text-slate-900 antialiased', inter.className)}>
      <body className="min-h-screen">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
